apiVersion: apps/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: prometheus
spec:
  containers:
    - name: prometheus
      resources:
        limits:
          cpu: “700m”
          memory: "2000Mi"
        requests:
          cpu: “100m”
          memory: "1500Mi"