apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: prometheus
spec:
  resources:
    limits:
      cpu: “1000m”
      memory: "3000Mi"
    requests:
      cpu: “100m”
      memory: "1500Mi"