apiVersion: apps/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: prometheus
spec:
  containers:
    - name: prometheus
      resources:
        limits:
          cpu: “1500m”
          memory: "4000Mi"
        requests:
          cpu: “1000m”
          memory: "2000Mi"