apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- networkpolicy.yaml
- prometheusrule.yaml
- persistentvolumeclaim.yaml
- service.yaml
- serviceaccount.yaml
- servicemonitor.yaml