apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-volume
  annotations:
    volume.autoscaler.kubernetes.io/scale-above-percent: "80"
    volume.autoscaler.kubernetes.io/scale-up-percent: "20"
  labels:
    app: prometheus
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: prometheus-gp3
  resources:
    requests:
      storage: 30Gi