apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubernetes-apiservers
  labels:
    prometheus: agent
spec:
  jobLabel: kubernetes-apiservers
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - relabelings:
      - sourceLabels: [ __meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name ]
        action: keep
        regex: default;kubernetes;https
      scheme: https
      authorization:
        credentials:
          name: prometheus-token
          key: token
      tlsConfig:
        ca:
          secret:
            name: prometheus-token
            key: ca.crt
  selector: {}