apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: cadvisor
  labels:
    prometheus: system-monitoring-prometheus
spec:
  scheme: HTTPS
  authorization:
    credentials:
      name: prometheus-token
      key: token
  tlsConfig:
    ca:
      secret:
        name: prometheus-token
        key: ca.crt
  relabelings:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - targetLabel: __address__
      replacement: kubernetes.default.svc:443
    - sourceLabels: [__meta_kubernetes_node_name]
      regex: (.+)
      targetLabel: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
  kubernetesSDConfigs:
  - role: Node
