apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kubernetes-pods
  labels:
    prometheus: agent
spec:
  jobLabel: kubernetes-pods
  namespaceSelector:
    any: true
  selector: {}
  podMetricsEndpoints:
    - tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - sourceLabels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape ]
          action: keep
          regex: "true"
        - sourceLabels: [ __meta_kubernetes_pod_annotation_prometheus_io_path ]
          targetLabel: __metrics_path__
          regex: (.+)
        - sourceLabels: [ __address__, __meta_kubernetes_pod_annotation_prometheus_io_port ]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          targetLabel: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - sourceLabels: [ __meta_kubernetes_namespace ]
          action: replace
          targetLabel: kubernetes_namespace
        - sourceLabels: [ __meta_kubernetes_pod_name ]
          action: replace
          targetLabel: instance