apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  labels:
    prometheus: agent
spec:
  jobLabel: kube-state-metrics
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
    - port: http-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
