apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  containers:
    - name: prometheus
      envFrom:
        - configMapRef:
            name: prometheus-environment-variables
  securityContext:
    fsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
  serviceAccountName: prometheus
  externalLabels:
    k8s_cluster_name: ${CLUSTER_NAME}-${TENANT_NAME}-${REGION_NICK_NAME}
  scrapeConfigSelector:
    matchLabels:
      prometheus: system-monitoring-prometheus
  image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/prom/prometheus:v2.47.0
  resources:
    limits:
      cpu: 1500m
      memory: 5500Mi
    requests:
      cpu: 100m
      memory: 2000Mi
  enableAdminAPI: false
  scrapeInterval: 30s
  scrapeTimeout: 5s
  retention: 15d
  enableRemoteWriteReceiver: true
  enableFeatures:
  - expand-external-labels
  - memory-snapshot-on-shutdown
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus-storage-volume
        annotations:
          volume.autoscaler.kubernetes.io/scale-above-percent: "80"
          volume.autoscaler.kubernetes.io/scale-up-percent: "20"
        labels:
          app: prometheus
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: prometheus-gp3
        resources:
          requests:
            storage: 30Gi